# Generated by Django 5.0.4 on 2024-05-25 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('#264653', 'Темно-синий'), ('#2A9D8F', 'Циановый'), ('#E9C46A', 'Жёлтый'), ('#E76F51', 'Красный'), ('#F4A261', 'Оранжевый'), ('#A260CA', 'Фиолетовый')], default='#264653')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_note', 'Создание заметки'), ('edit_note', 'Редактирование заметки'), ('delete_note', 'Удаление заметки'), ('restore_note', 'Восстановление заметки'), ('create_category', 'Создание категории'), ('edit_category', 'Редактирование категории'), ('delete_category', 'Удаление категории')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/%Y/%m/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='noteapp.report')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_font', models.CharField(choices=[('JetBrains Mono', 'JetBrains Mono'), ('Nunito', 'Nunito'), ('Fira Code', 'Fira Code'), ('Roboto Thin', 'Roboto Thin'), ('Source Code Pro', 'Source Code Pro')], default='JetBrains Mono', max_length=20)),
                ('code_font_size', models.IntegerField(choices=[(12, '12'), (14, '14'), (16, '16'), (18, '18')], default=14)),
                ('text_font', models.CharField(choices=[('JetBrains Mono', 'JetBrains Mono'), ('Nunito', 'Nunito'), ('Fira Code', 'Fira Code'), ('Roboto Thin', 'Roboto Thin'), ('Source Code Pro', 'Source Code Pro')], default='JetBrains Mono', max_length=20)),
                ('text_font_size', models.IntegerField(choices=[(12, '12'), (14, '14'), (16, '16'), (18, '18')], default=16)),
                ('code_theme', models.CharField(choices=[('a11y-dark', 'a11y-dark'), ('atom-one-dark', 'atom-one-dark'), ('isbl-editor-dark', 'isbl-editor-dark'), ('agate', 'agate')], default='a11y-dark', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='noteapp.setting'),
        ),
    ]
