# Generated by Django 5.0.4 on 2024-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('#264653', 'Темно-синий'), ('#2A9D8F', 'Циановый'), ('#E9C46A', 'Жёлтый'), ('#E76F51', 'Красный'), ('#F4A261', 'Оранжевый'), ('#A260CA', 'Фиолетовый')], default='#A260CA', null=True),
        ),
    ]
