# Generated by Django 5.0.4 on 2024-05-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0003_category_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, choices=[('', 'Выберите цвет'), ('#264653', 'Темно-синий'), ('#2A9D8F', 'Циановый'), ('#E9C46A', 'Жёлтый'), ('#E76F51', 'Красный'), ('#F4A261', 'Оранжевый'), ('#A260CA', 'Фиолетовый')], null=True),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_font', models.CharField(blank=True, choices=[('JetBrains Mono', 'JetBrains Mono'), ('Nunito', 'Nunito'), ('Fira Code', 'Fira Code'), ('Roboto Thin', 'Roboto Thin'), ('Source Code Pro', 'Source Code Pro')], default='JetBrains Mono', max_length=20, null=True)),
                ('code_font_size', models.IntegerField(blank=True, choices=[(12, '12'), (14, '14'), (16, '16'), (18, '18')], default=14, null=True)),
                ('text_font', models.CharField(blank=True, choices=[('JetBrains Mono', 'JetBrains Mono'), ('Nunito', 'Nunito'), ('Fira Code', 'Fira Code'), ('Roboto Thin', 'Roboto Thin'), ('Source Code Pro', 'Source Code Pro')], default='JetBrains Mono', max_length=20, null=True)),
                ('text_font_size', models.IntegerField(blank=True, choices=[(12, '12'), (14, '14'), (16, '16'), (18, '18')], default=16, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
