# Generated by Django 5.0.4 on 2024-05-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0005_alter_setting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile', unique=True),
        ),
    ]
