# Generated by Django 5.0.4 on 2024-05-14 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0007_profile_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile'),
        ),
    ]
