# Generated by Django 5.0.4 on 2024-05-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0009_alter_setting_code_font_alter_setting_code_font_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('#264653', 'Темно-синий'), ('#2A9D8F', 'Циановый'), ('#E9C46A', 'Жёлтый'), ('#E76F51', 'Красный'), ('#F4A261', 'Оранжевый'), ('#A260CA', 'Фиолетовый')], default='#264653'),
        ),
    ]
