# Generated by Django 5.0.4 on 2024-05-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0010_alter_category_author_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
