# Generated by Django 5.0.4 on 2024-05-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0011_alter_note_icon_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='code_theme',
            field=models.CharField(choices=[('JetBrains Mono', 'JetBrains Mono'), ('Nunito', 'Nunito'), ('Fira Code', 'Fira Code'), ('Roboto Thin', 'Roboto Thin'), ('Source Code Pro', 'Source Code Pro')], default='a11y-dark', max_length=20),
        ),
    ]
