# Generated by Django 5.0.4 on 2024-05-19 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0012_setting_code_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.category'),
        ),
        migrations.AlterField(
            model_name='note',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='code_theme',
            field=models.CharField(choices=[('a11y-dark', 'a11y-dark'), ('atom-one-dark', 'atom-one-dark'), ('isbl-editor-dark', 'isbl-editor-dark'), ('agate', 'agate')], default='a11y-dark', max_length=20),
        ),
    ]
