# Generated by Django 5.0.4 on 2024-05-21 09:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0013_note_is_deleted_alter_note_category_alter_note_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_note', 'Создание заметки'), ('edit_note', 'Редактирование заметки'), ('delete_note', 'Удаление заметки'), ('restore_note', 'Восстановление заметки'), ('create_category', 'Создание категории'), ('edit_category', 'Редактирование категории'), ('delete_category', 'Удаление категории')], max_length=50)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noteapp.profile')),
            ],
        ),
    ]
